version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: on-failure
    depends_on:
      my_database:
          condition: service_healthy
    environment:
      MYSQL_HOST: my_database
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: my_db
      MYSQL_PORT: 3302
    command: npm run dev -- --port 3000 --host 0.0.0.0
    ports:
      - "3332:3000"
    networks:
      - my_custom_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: on-failure
    command: npm run dev -- --port 4000 --host 0.0.0.0
    ports:
      - "1212:4000"
    networks:
      - my_custom_network

  my_database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppass" ]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "3302:3306"
    networks:
      - my_custom_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - my_database
    environment:
      PMA_HOST: my_database
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "2111:80"
    links: 
      - my_database
    networks:
      - my_custom_network

networks:
    my_custom_network:

